# Generated by Django 2.2.7 on 2019-11-18 13:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('definition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_number', models.IntegerField(blank=True, default=0, null=True, verbose_name='Employee Number')),
                ('emp_name', models.CharField(max_length=60, verbose_name='Employee Name')),
                ('address1', models.CharField(blank=True, max_length=255, null=True, verbose_name='address1')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='phone')),
                ('mobile', models.CharField(blank=True, max_length=255, null=True, verbose_name='mobile')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Birthdate')),
                ('hiredate', models.DateField(default=datetime.date.today, verbose_name='Hire Date')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='', verbose_name='picture')),
                ('id_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Number')),
                ('place_of_birth', models.CharField(blank=True, max_length=100, null=True, verbose_name='Place of Birth')),
                ('nationality', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nationality')),
                ('field_of_study', models.CharField(blank=True, max_length=30, null=True, verbose_name='Field of Study')),
                ('education_degree', models.CharField(blank=True, max_length=30, null=True, verbose_name='Eductaion Degree')),
                ('insured', models.BooleanField(verbose_name='Insured')),
                ('insurance_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='Insurance Number')),
                ('insurance_date', models.DateField(blank=True, null=True, verbose_name='Insurance Date')),
                ('has_medical', models.BooleanField(verbose_name='Has Medical')),
                ('medical_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='Medical Number')),
                ('medical_date', models.DateField(blank=True, null=True, verbose_name='Medical Date')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('creation_date', models.DateField(auto_now=True)),
                ('last_update_date', models.DateField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_created_by', to=settings.AUTH_USER_MODEL)),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gender_list', to='definition.LookupDet', verbose_name='Gender')),
                ('identification_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_id_type', to='definition.LookupDet', verbose_name='ID Type')),
                ('last_update_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('military_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_military', to='definition.LookupDet', verbose_name='Milatery Status')),
                ('religion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_religion', to='definition.LookupDet', verbose_name='Religion')),
                ('social_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_social', to='definition.LookupDet', verbose_name='Social Status')),
            ],
        ),
        migrations.CreateModel(
            name='Job_Roll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('reason_of_leaving', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_date', models.DateField(auto_now=True)),
                ('last_update_date', models.DateField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobRoll_created_by', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Department', verbose_name='Department')),
                ('emp_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_roll_emp', to='employee.Employee', verbose_name='Employee')),
                ('emp_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='definition.LookupDet', verbose_name='Employee Type')),
                ('job_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Job', verbose_name='Job Name')),
                ('last_update_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobroll_last_updated_by', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_roll_manager', to='employee.Employee', verbose_name='Manager')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Position', verbose_name='Position')),
            ],
        ),
    ]
