# Generated by Django 2.2.7 on 2019-11-20 07:51

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('definition', '0001_initial'),
        ('employee', '0002_auto_20191120_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_attachment',
            name='attachment_name',
            field=models.CharField(max_length=150, verbose_name='Attachment Name'),
        ),
        migrations.CreateModel(
            name='Employee_Leaves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaves_deserved', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(52), django.core.validators.MinValueValidator(0)])),
                ('abscent_days', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(52), django.core.validators.MinValueValidator(0)])),
                ('reason', models.CharField(max_length=150, verbose_name='Leave Reason')),
                ('leave_balance', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(52), django.core.validators.MinValueValidator(0)])),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('creation_date', models.DateField(auto_now=True)),
                ('last_update_date', models.DateField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_leaves_created_by', to=settings.AUTH_USER_MODEL)),
                ('emp_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaves_emp', to='employee.Employee', verbose_name='Employee')),
                ('last_update_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_leaves_last_updated_by', to=settings.AUTH_USER_MODEL)),
                ('leave_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_leave_type', to='definition.LookupDet', verbose_name='Leave Type')),
            ],
        ),
    ]
