# Generated by Django 2.2.7 on 2019-11-20 08:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20191120_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_leaves',
            name='leaves_deserved',
        ),
        migrations.RemoveField(
            model_name='job_roll',
            name='department',
        ),
        migrations.RemoveField(
            model_name='job_roll',
            name='job_name',
        ),
        migrations.AddField(
            model_name='job_roll',
            name='leaves_deserved',
            field=models.PositiveIntegerField(default=21, validators=[django.core.validators.MaxValueValidator(52), django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
